/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WorldId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const World = IDL.Record({
  'id' : WorldId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'xpReward' : IDL.Nat,
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'worldId' : WorldId,
  'choices' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [WorldId, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
      [QuestionId],
      [],
    ),
  'addWorld' : IDL.Func([IDL.Text, IDL.Text], [WorldId], []),
  'getAllWorlds' : IDL.Func([], [IDL.Vec(World)], ['query']),
  'getPlayerStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'xp' : IDL.Nat,
          'completedQuestions' : IDL.Vec(QuestionId),
        }),
      ],
      ['query'],
    ),
  'getQuestionsForWorld' : IDL.Func([WorldId], [IDL.Vec(Question)], ['query']),
  'submitAnswer' : IDL.Func(
      [QuestionId, IDL.Nat],
      [IDL.Record({ 'correct' : IDL.Bool, 'xpEarned' : IDL.Nat })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WorldId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const World = IDL.Record({
    'id' : WorldId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'xpReward' : IDL.Nat,
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'worldId' : WorldId,
    'choices' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [WorldId, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Nat],
        [QuestionId],
        [],
      ),
    'addWorld' : IDL.Func([IDL.Text, IDL.Text], [WorldId], []),
    'getAllWorlds' : IDL.Func([], [IDL.Vec(World)], ['query']),
    'getPlayerStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'xp' : IDL.Nat,
            'completedQuestions' : IDL.Vec(QuestionId),
          }),
        ],
        ['query'],
      ),
    'getQuestionsForWorld' : IDL.Func(
        [WorldId],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'submitAnswer' : IDL.Func(
        [QuestionId, IDL.Nat],
        [IDL.Record({ 'correct' : IDL.Bool, 'xpEarned' : IDL.Nat })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };