/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Question {
  'id' : QuestionId,
  'xpReward' : bigint,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'worldId' : WorldId,
  'choices' : Array<string>,
}
export type QuestionId = bigint;
export interface World {
  'id' : WorldId,
  'name' : string,
  'description' : string,
}
export type WorldId = bigint;
export interface _SERVICE {
  'addQuestion' : ActorMethod<
    [WorldId, string, Array<string>, bigint, bigint],
    QuestionId
  >,
  'addWorld' : ActorMethod<[string, string], WorldId>,
  'getAllWorlds' : ActorMethod<[], Array<World>>,
  'getPlayerStats' : ActorMethod<
    [],
    { 'xp' : bigint, 'completedQuestions' : Array<QuestionId> }
  >,
  'getQuestionsForWorld' : ActorMethod<[WorldId], Array<Question>>,
  'submitAnswer' : ActorMethod<
    [QuestionId, bigint],
    { 'correct' : boolean, 'xpEarned' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];